spring:
  application:
    name: authentication-service
  datasource:
    url: ${AUTH_DB_URL}
    username: ${AUTH_DB_USERNAME}
    password: ${AUTH_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
server:
  port: 8181
jwt:
  secret: ${SECRET_KEY}
  expiration: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6767/eureka/