spring:
  application:
    name: event-service
  datasource:
    url: ${EVENT_DB_URL}
    username: ${EVENT_DB_USERNAME}
    password: ${EVENT_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
server:
  port: 8083
jwt:
  secret: ${SECRET_KEY}
  expiration: 3600000